# Generated by Django 2.1.1 on 2018-09-24 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('dni', models.IntegerField(default=0)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('telefono', models.BigIntegerField(default=0)),
                ('domicilio', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('tren', models.CharField(choices=[('Tren superior', 'Tren superior'), ('Tren inferior', 'Tren inferior')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('altura', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('mutual', models.CharField(default='', max_length=30)),
                ('observaciones', models.TextField(default='')),
                ('telefono_emergencia', models.BigIntegerField(default=0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rutinas.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de débito', 'Tarjeta de débito')], max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(choices=[('Suplemento', 'Suplemento'), ('Máquina', 'Máquina'), ('Insumo', 'Insumo'), ('Accesorio', 'Accesorio'), ('Alimento', 'Alimento'), ('Bebida', 'Bebida')], max_length=30)),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('num_matricula', models.IntegerField(default=0)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('telefono', models.BigIntegerField(default=0)),
                ('domicilio', models.CharField(default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('telefono', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso_levantado', models.IntegerField(default=0)),
                ('repeticiones', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Cliente')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sesiones', models.CharField(choices=[('3 días', '3 días'), ('5 días', '5 días')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Cliente')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Rutina')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('domicilio', models.CharField(default='', max_length=30)),
                ('telefono', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Rutina'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Sucursal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Profesor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rutinas',
            field=models.ManyToManyField(to='rutinas.Rutina'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrador',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Sucursal'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
