# Generated by Django 2.1.1 on 2019-01-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rutinas',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rutinas',
            field=models.ManyToManyField(blank=True, through='rutinas.RutinaCliente', to='rutinas.Rutina'),
        ),
    ]
