# Generated by Django 2.1.1 on 2018-09-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rutinas',
            field=models.ManyToManyField(blank=True, to='rutinas.Rutina'),
        ),
    ]
