# Generated by Django 2.1.1 on 2018-12-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
