# Generated by Django 2.1.1 on 2018-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='altura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='mutual',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='observaciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='telefono_emergencia',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profesor',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profesor',
            name='num_matricula',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='peso_levantado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='repeticiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='domicilio',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='domicilio',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
