# Generated by Django 2.1.1 on 2018-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_auto_20181218_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='num_tarjeta',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
