# Generated by Django 2.1.1 on 2018-09-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_auto_20180924_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(default=0, help_text='Introduzca un número de teléfono válido'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='altura',
            field=models.IntegerField(help_text='Ingrese la altura en centímetros'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='peso',
            field=models.IntegerField(help_text='Ingrese el peso en kg'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='telefono_emergencia',
            field=models.BigIntegerField(default=0, help_text='Introduzca un número de teléfono válido'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.BigIntegerField(default=0, help_text='Introduzca un número de teléfono válido'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(default=0, help_text='Introduzca un número de teléfono válido'),
        ),
    ]
