# Generated by Django 2.1.1 on 2018-12-11 17:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rutinas', '0002_auto_20181210_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='profesor',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profesor',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='calificacion_promedio',
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('content_type', 'object_id')},
        ),
    ]
