# Generated by Django 2.1.2 on 2019-01-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_auto_20190109_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('peso_levantado', models.IntegerField(default=0)),
                ('repeticiones', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='peso_levantado',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='repeticiones',
        ),
        migrations.AddField(
            model_name='registro',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Serie'),
        ),
    ]
