# Generated by Django 2.1.1 on 2019-01-21 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_auto_20190109_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ('-creado',)},
        ),
        migrations.AddField(
            model_name='articulo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterIndexTogether(
            name='articulo',
            index_together={('id', 'slug')},
        ),
    ]
