# Generated by Django 2.1.1 on 2018-12-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_auto_20181218_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='num_tarjeta',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
