# Generated by Django 2.1.1 on 2018-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_auto_20180925_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(to='rutinas.Ejercicio'),
        ),
    ]
