# Generated by Django 2.1.1 on 2018-12-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_auto_20181213_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicios', models.ManyToManyField(blank=True, to='rutinas.Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='DiaEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Dia')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutinas.Ejercicio')),
            ],
        ),
    ]
