# Generated by Django 2.1.1 on 2019-01-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_auto_20190121_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='articulo',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='slug',
        ),
    ]
