# Generated by Django 2.1.1 on 2018-12-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_auto_20181221_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='', upload_to='foto_perfil'),
        ),
    ]
