# Generated by Django 2.1.1 on 2018-12-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_auto_20181228_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='numero',
        ),
    ]
