# Generated by Django 2.1.1 on 2019-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_auto_20190123_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
