# Generated by Django 2.1.1 on 2018-12-17 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_dia_diaejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaejercicio',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='diaejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='ejercicios',
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='dia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Dia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DiaEjercicio',
        ),
    ]
