# Generated by Django 2.1.1 on 2018-09-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_rutina_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='gif',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
