# Generated by Django 2.1.1 on 2018-12-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_auto_20181216_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='sesiones',
        ),
        migrations.AddField(
            model_name='rutina',
            name='dias',
            field=models.ManyToManyField(to='rutinas.Dia'),
        ),
    ]
