# Generated by Django 2.1.1 on 2019-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_auto_20190123_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(default='', upload_to='foto_perfil'),
        ),
    ]
