# Generated by Django 2.1.1 on 2018-12-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_diaejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
