# Generated by Django 2.1.1 on 2018-12-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_auto_20181216_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='tren',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicios',
        ),
        migrations.AddField(
            model_name='dia',
            name='ejercicios',
            field=models.ManyToManyField(to='rutinas.Ejercicio'),
        ),
        migrations.AddField(
            model_name='dia',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
