# Generated by Django 2.1.1 on 2018-12-18 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0008_auto_20181217_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='dias',
        ),
        migrations.AddField(
            model_name='dia',
            name='rutina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Rutina'),
            preserve_default=False,
        ),
    ]
