# Generated by Django 2.1.1 on 2019-01-31 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0009_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.Administrador'),
        ),
    ]
