# Generated by Django 2.1.1 on 2019-01-31 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0010_auto_20190131_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='num_tarjeta',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(1111111111111111)]),
        ),
    ]
