# Generated by Django 2.1.1 on 2018-12-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0010_rutina_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.Rutina'),
        ),
    ]
