# Generated by Django 2.1.1 on 2018-12-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0011_auto_20181217_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.CharField(default='', max_length=250),
        ),
    ]
