# Generated by Django 2.1.1 on 2019-02-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_auto_20190109_2058'),
        ('rutinas', '0011_auto_20190131_1638'),
    ]

    operations = [
    ]
