# Generated by Django 2.1.1 on 2019-02-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0012_merge_20190206_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='serie',
        ),
        migrations.AddField(
            model_name='serie',
            name='registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Registro'),
        ),
    ]
