# Generated by Django 2.1.1 on 2018-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0012_ejercicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
