# Generated by Django 2.1.1 on 2018-12-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0013_auto_20181217_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinacliente',
            name='actual',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
