# Generated by Django 2.1.1 on 2019-02-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0013_auto_20190206_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Registro')),
            ],
        ),
        migrations.RemoveField(
            model_name='serie',
            name='registro',
        ),
        migrations.AddField(
            model_name='semana',
            name='serie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rutinas.Serie'),
        ),
    ]
