# Generated by Django 2.1.1 on 2018-12-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0014_rutinacliente_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
