# Generated by Django 2.1.1 on 2019-02-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0014_auto_20190206_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semana',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='semana',
            name='serie',
        ),
        migrations.AddField(
            model_name='registro',
            name='semana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Semana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semana',
            name='rutina_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutinas.RutinaCliente'),
        ),
        migrations.AddField(
            model_name='serie',
            name='semana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutinas.Semana'),
            preserve_default=False,
        ),
    ]
