# Generated by Django 2.1.1 on 2019-02-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0015_auto_20190206_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='numero',
        ),
    ]
