# Generated by Django 2.1.5 on 2019-02-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0016_remove_rutina_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='semana',
        ),
        migrations.AddField(
            model_name='registro',
            name='rutina_ejercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rutinas.RutinaEjercicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semana',
            name='dias',
            field=models.ManyToManyField(to='rutinas.Dia'),
        ),
        migrations.AddField(
            model_name='serie',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutinas.Registro'),
            preserve_default=False,
        ),
    ]
