# Generated by Django 2.1.5 on 2019-02-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0018_auto_20190210_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='semana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutinas.Semana'),
        ),
    ]
