# Generated by Django 2.1.1 on 2019-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0019_auto_20190210_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
