# Generated by Django 2.1.1 on 2019-02-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0020_auto_20190219_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(default='', upload_to='foto_perfil'),
        ),
    ]
