# Generated by Django 2.1.1 on 2019-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0021_auto_20190219_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='', upload_to='foto_perfil'),
        ),
    ]
