# Generated by Django 3.0.8 on 2020-07-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.Client"
            ),
        ),
        migrations.AddField(
            model_name="routineclient",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="routines.Routine"
            ),
        ),
        migrations.AddField(
            model_name="register",
            name="routine_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="routines.RoutineExercise",
            ),
        ),
        migrations.AddField(
            model_name="register",
            name="week",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="routines.Week",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="exercises",
            field=models.ManyToManyField(to="routines.Exercise"),
        ),
        migrations.AddField(
            model_name="day",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="routines.Routine"
            ),
        ),
    ]
