# Generated by Django 3.0.8 on 2020-07-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(default=django.utils.timezone.now)),
                ("dni", models.IntegerField(default=0)),
                (
                    "profile_picture",
                    models.ImageField(default="", upload_to="foto_perfil"),
                ),
                (
                    "phone",
                    models.BigIntegerField(
                        default=0, help_text="Introduzca un número de teléfono válido"
                    ),
                ),
                ("address", models.CharField(default="", max_length=30)),
                (
                    "routines",
                    models.ManyToManyField(
                        blank=True,
                        through="routines.RoutineClient",
                        to="routines.Routine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.IntegerField(default=0)),
                (
                    "profile_picture",
                    models.ImageField(default="", upload_to="foto_perfil"),
                ),
                (
                    "phone",
                    models.BigIntegerField(
                        default=0, help_text="Introduzca un número de teléfono válido"
                    ),
                ),
                ("address", models.CharField(default="", max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="users.Trainer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(help_text="Ingrese la altura en centímetros"),
                ),
                ("weight", models.IntegerField(help_text="Ingrese el peso en kg")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        max_length=20,
                    ),
                ),
                ("health_insurance", models.CharField(default="", max_length=30)),
                ("comments", models.TextField(default="")),
                (
                    "emergency_phone",
                    models.BigIntegerField(
                        default=0, help_text="Introduzca un número de teléfono válido"
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.Client"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.Trainer"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="BranchManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.Branch"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
