# Generated by Django 3.0.8 on 2020-07-09 02:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="trainer",),
        migrations.RemoveField(model_name="medicalrecord", name="client",),
        migrations.RemoveField(model_name="medicalrecord", name="gender",),
        migrations.AddField(
            model_name="client", name="client_since", field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="client",
            name="client_until",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client", name="is_active", field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="medical_record",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="users.MedicalRecord",
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trainer", name="employee_since", field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="employee_until",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainer", name="is_active", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="dni",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un DNI válido", regex="^\\d{8}"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="profile_picture",
            field=models.ImageField(blank=True, default="", null=True, upload_to="foto_perfil"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="dni",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un DNI válido", regex="^\\d{8}"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="profile_picture",
            field=models.ImageField(blank=True, default="", null=True, upload_to="foto_perfil"),
        ),
    ]
