# Generated by Django 3.0 on 2020-07-02 00:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
                ("apellido", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Articulo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(db_index=True, max_length=250)),
                ("descripcion", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calificacion", models.IntegerField(default=0)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
                ("apellido", models.CharField(default="", max_length=30)),
                ("foto", models.ImageField(default="", upload_to="foto_perfil")),
                ("dni", models.IntegerField(default=0)),
                ("mail", models.EmailField(default="", max_length=254)),
                ("telefono", models.BigIntegerField(default=0, help_text="Introduzca un número de teléfono válido")),
                ("domicilio", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Dia",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),],
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
                ("descripcion", models.TextField(default="")),
                ("gif", models.ImageField(default="", upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
                ("apellido", models.CharField(default="", max_length=30)),
                ("mail", models.EmailField(default="", max_length=254)),
                ("telefono", models.BigIntegerField(default=0, help_text="Introduzca un número de teléfono válido")),
            ],
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("completado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rutina",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="RutinaCliente",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actual", models.BooleanField()),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Cliente")),
                ("rutina", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Rutina")),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
                ("domicilio", models.CharField(default="", max_length=30)),
                ("telefono", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "articulo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rutinas.Articulo",
                    ),
                ),
                ("imagen", models.ImageField(default="", upload_to="")),
            ],
            bases=("rutinas.articulo",),
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=7)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Tarjeta de crédito", "Tarjeta de crédito"),
                            ("Tarjeta de débito", "Tarjeta de débito"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "num_tarjeta",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999999999),
                            django.core.validators.MinValueValidator(1111111111111111),
                        ],
                    ),
                ),
                (
                    "administrador",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="rutinas.Administrador"
                    ),
                ),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rutinas.Cliente")),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.IntegerField(default=1)),
                ("peso_levantado", models.IntegerField(default=0)),
                ("repeticiones", models.IntegerField(default=0)),
                ("registro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rutinas.Registro")),
            ],
        ),
        migrations.CreateModel(
            name="Semana",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.IntegerField(default=1)),
                ("dias", models.ManyToManyField(to="rutinas.Dia")),
                (
                    "rutina_cliente",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="rutinas.RutinaCliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RutinaEjercicio",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dia", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Dia")),
                ("ejercicio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Ejercicio")),
                ("rutina", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Rutina")),
            ],
        ),
        migrations.AddField(
            model_name="registro",
            name="rutina_ejercicio",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.RutinaEjercicio"),
        ),
        migrations.AddField(
            model_name="registro",
            name="semana",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="rutinas.Semana"),
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=30)),
                ("apellido", models.CharField(default="", max_length=30)),
                ("num_matricula", models.IntegerField(default=0)),
                ("foto", models.ImageField(default="", upload_to="foto_perfil")),
                ("mail", models.EmailField(default="", max_length=254)),
                ("telefono", models.BigIntegerField(default=0, help_text="Introduzca un número de teléfono válido")),
                ("domicilio", models.CharField(default="", max_length=30)),
                ("calificacion_promedio", models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaMedica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_nacimiento", models.DateField(default=django.utils.timezone.now)),
                ("altura", models.IntegerField(help_text="Ingrese la altura en centímetros")),
                ("peso", models.IntegerField(help_text="Ingrese el peso en kg")),
                (
                    "sexo",
                    models.CharField(choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")], max_length=20),
                ),
                ("mutual", models.CharField(default="", max_length=30)),
                ("observaciones", models.TextField(default="")),
                (
                    "telefono_emergencia",
                    models.BigIntegerField(default=0, help_text="Introduzca un número de teléfono válido"),
                ),
                ("cliente", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="rutinas.Cliente")),
            ],
        ),
        migrations.AddField(model_name="dia", name="ejercicios", field=models.ManyToManyField(to="rutinas.Ejercicio"),),
        migrations.AddField(
            model_name="dia",
            name="rutina",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rutinas.Rutina"),
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                ("desde", models.DateField(blank=True, null=True)),
                ("hasta", models.DateField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=7)),
                ("articulo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rutinas.Articulo")),
                ("pago", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rutinas.Venta")),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="profesor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Profesor"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rutinas",
            field=models.ManyToManyField(blank=True, through="rutinas.RutinaCliente", to="rutinas.Rutina"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="administrador",
            name="sucursal",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Sucursal"),
        ),
        migrations.AddField(
            model_name="administrador",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "articulo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rutinas.Articulo",
                    ),
                ),
                ("imagen", models.ImageField(default="", upload_to="")),
                ("stock", models.IntegerField(default=0)),
                (
                    "tipo_producto",
                    models.CharField(
                        choices=[
                            ("Suplemento", "Suplemento"),
                            ("Máquina", "Máquina"),
                            ("Insumo", "Insumo"),
                            ("Accesorio", "Accesorio"),
                            ("Alimento", "Alimento"),
                            ("Bebida", "Bebida"),
                        ],
                        max_length=30,
                    ),
                ),
                ("proveedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Proveedor")),
                ("sucursal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rutinas.Sucursal")),
            ],
            bases=("rutinas.articulo",),
        ),
    ]
